### ISSUE TITLE
BitcoinMerchant SSR missing user in ctx is front-and-center now

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#237] opened 2018-05-05 17:04 UTC

**Comment by khardenstine** [comment] 2018-05-05 17:36
Duplicate of https://github.com/hyperfiddle/hyperfiddle.net/issues/112

**Closed by khardenstine** 2018-05-05 17:36 UTC

**Comment by dustingetz** [comment] 2018-05-15 14:58
No longer front and center, because I tweaked bitcoin merchant to not use the ctx on the merchant homepage but rather get it from the url.
