### ISSUE TITLE
Dangling load spinner after transact

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#736] opened 2018-11-13 15:16 UTC
Reproduce:
- http://tank.hyperfiddle.site/
- add whitespace to the query
- wait for stage to turn yellow
- transact 
- observe js error and dangling spinner

```
bluebird.js:1542 Unhandled rejection Error: nth not supported on this type cljs.core/PersistentArrayMap    at Function.cljs$core$IFn$_invoke$arity$3 (http://tank.hyperfiddle.site/static/dev/main.out/cljs/core.js:6283:8)    at cljs$core$nth (http://tank.hyperfiddle.site/static/dev/main.out/cljs/core.js:6175:22)    at hypercrud$browser$routing$invert_route (http://tank.hyperfiddle.site/static/dev/main.out/hypercrud/browser/routing.js:24:23)    at http://tank.hyperfiddle.site/static/dev/main.out/hyperfiddle/actions.js:390:65
```

![image](https://user-images.githubusercontent.com/124158/48422625-119f5780-e72d-11e8-8aa6-835aad31acd6.png)

**Comment by dustingetz** [comment] 2018-11-13 15:17
The js error is only on my local. The dangling spinner is repro in prod rn. Maybe the js error is unrelated

**Comment by khardenstine** [comment] 2018-11-15 14:29
Fixed in my routing changes.  Caused by broken argument order:
https://github.com/hyperfiddle/hyperfiddle/commit/45031cf2a8c2f5464bf25ce16cccb32f65f9e13e#diff-70f0b48445092337af611e55fd7ec0b1L188

**Closed by khardenstine** 2018-11-15 14:29 UTC
