### ISSUE TITLE
"duplicate key" in a simple query

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#678] opened 2018-10-05 22:53 UTC
http://tank.hyperfiddle.net/:mbrainz/ toggle to view. maybe i am tired

**Comment by khardenstine** [comment] 2018-10-06 00:10
This is a hash collision on integers when computing [react keys](https://github.com/hyperfiddle/hyperfiddle/blob/83d9acdc3aa98fb274a4f27f529c307940a863bf/src/hyperfiddle/data.cljc#L21)
```js
x = [/* insert db/ids from api view*/]
x.length
4601
[...new Set(x.map(cljs.core.hash))].length
4561
```

Related #298

**Comment by dustingetz** [comment] 2018-10-25 15:47
Couldn't easily reproduce

**Comment by khardenstine** [comment] 2018-12-05 15:17
Duplicate of #298

**Closed by khardenstine** 2018-12-05 15:17 UTC
Labels: bug
