### ISSUE TITLE
attribute editor can silently fail to transact cardinality & valuetype

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#32] opened 2018-01-29 16:22 UTC
It has something to do with also setting the docstring. The UI then looks right, and looks like it stages right, but only the db/ident was staged and transacted. Once I noticed that the attribute was not installed in the schema, I tried to add the valueType and Cardinality and received
`java.lang.IllegalArgumentException: :db.error/not-in-system-partition Value of :db.install/attribute must be in :db.part/db partition, found :trulioo.v1.person-info/day-of-birth"}`

**Comment by dustingetz** [comment] 2018-01-29 16:24
I was able to repair it with `[:db/retract :trulioo.v1.person-info/day-of-birth :db/ident :trulioo.v1.person-info/day-of-birth]` and then start over

**Comment by khardenstine** [comment] 2018-01-29 17:33
Reproduced by entering data in the following order:

1. doc
2. valueType
3. ident
4. cardinality

**Comment by khardenstine** [comment] 2018-01-29 17:45
The attribute-edit renderer is not being fired due to Entity equality changes.  The component could probably be rewritten, but finishing the reactivity changes should also fix this

**Comment by khardenstine** [comment] 2018-03-07 19:23
Fixed with #7

**Closed by khardenstine** 2018-03-07 19:23 UTC
Labels: bug
