### ISSUE TITLE
Fiddle ontology changes need to propogate to user repos

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#102] opened 2018-02-27 16:19 UTC
User repo dbs need migration and it's not okay to transact to databases we don't own. The IDE behavior is not defined until they have the ontology change. For simple things like :fiddle/css which is pull-only, its just a corrupted form

![image](https://user-images.githubusercontent.com/124158/36740245-e3818498-1baf-11e8-9f2f-908e877c7ac9.png)

**Comment by khardenstine** [comment] 2018-03-30 22:03
Duplicate of hyperfiddle/hyperfiddle.net#24

**Closed by khardenstine** 2018-03-30 22:03 UTC
